version: '3.4'

services:
  
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.7-alpine
    env_file:
     - ./dev.env
    ports:
      - "5672:5672"
    restart: on-failure

  postgres:
    image: postgres:11.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ./dev.env
    ports:
      - "5432:5432"
    restart: on-failure
    

  web:
    build: .
    working_dir: /usr/src/pics/pics
    command: gunicorn pics.wsgi:application -w 2 -b :8000
    container_name: pictures_box
    depends_on:
      - postgres
      - rabbitmq
    env_file:
     - ./dev.env
    ports:
      - "8000:8000"
    hostname: pictures
    image: pics_image
    restart: on-failure
    env_file:
      - ./dev.env
    volumes:
      - web-media:/usr/src/pics/media

  worker:
    build: .
    image: pics_image
    restart: on-failure
    working_dir: /usr/src/pics/pics
    env_file:
      - ./dev.env
    command: celery worker --app=worker.worker.app -l info
    volumes:
      - web-media:/usr/src/pics/media
    depends_on:
      - rabbitmq

volumes:
  postgres_data:
  web-media:
