# Generated by Django 2.2.7 on 2019-11-10 19:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20191109_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
