# Generated by Django 2.2.7 on 2019-11-11 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0003_note_ctime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('user', 'picture')},
        ),
    ]
